image: python:2.7-slim

before_script:
  - python -V

test:
  variables:
    SELENIUM_HUB: 'selenium-grid'
  script:
  - pip install -r requirements.txt
  - pytest --driver Remote --capability browserName chrome --host ${SELENIUM_HUB}



