image: python:2.7

before_script:
  - python -V

test:
  variables:
    SELENIUM_HUB: 'selenium-grid'
  script:
  - pip install -r requirements.txt
  - RUNNER_IP=`hostname -I` pytest --driver Remote --capability browserName chrome --host ${SELENIUM_HUB} test_homepage.py



