image: sterago/idi2018

before_script:
  - python -V

test:
  variables:
    SELENIUM_HUB: 'selenium-grid'
  script:
  - RUNNER_IP=`hostname -I` pytest --driver Remote --capability browserName chrome --host ${SELENIUM_HUB} --needle-engine perceptualdiff test_homepage.py
  artifacts:
      paths:
      - screenshots/
      when: always

