image: python:2.7-slim

before_script:
  - python -V

test:
  variables:
    SELENIUM_HUB: 'selenium-grid'
    CI_DEBUG_TRACE: "true"
  script:
  - pip install -r requirements.txt
  - echo `hostname -I`
  - pytest --driver Remote --capability browserName chrome --host ${SELENIUM_HUB}



