image: sterago/idi2018

before_script:
  - python -V

install backend dependencies:
  stage: install

install frontend dependencies:
  stage: install

build frontend assets:
  stage: build

unit tests:
  stage: unit and integration tests
  script:
  - echo "unit tests ran"

integration tests:
  stage: unit and integration tests
  script:
  - echo "integration tests ran"

visual tests:
  stage: visual tests
  variables:
    SELENIUM_HUB: 'selenium-grid'
  script:
  - RUNNER_IP=`hostname -I` pytest --driver Remote --capability browserName chrome --host ${SELENIUM_HUB} --needle-engine perceptualdiff test_homepage.py
  artifacts:
      paths:
      - screenshots/
      when: always

deploy:
  script:
  - echo "deploy"

stages:
  - install
  - build
  - unit and integration tests
  - visual tests
  - deploy