
install backend dependencies:
  stage: install
  script:
  - echo "installing backend dependencies"

install frontend dependencies:
  stage: install
  script:
  - echo "installing frontend dependencies"

build frontend assets:
  stage: build
  script:
  - echo "building frontend assets"

unit tests:
  stage: unit and integration tests
  script:
  - echo "unit tests ran"

integration tests:
  stage: unit and integration tests
  script:
  - echo "integration tests ran"

visual tests:
  stage: visual tests
  image: sterago/idi2018
  variables:
    SELENIUM_HUB: 'selenium-grid'
  script:
  - RUNNER_IP=`hostname -I` pytest --driver Remote --capability browserName chrome --host ${SELENIUM_HUB} --needle-engine perceptualdiff visual_tests/
  artifacts:
      paths:
      - screenshots/
      when: always
  tags:
   - visual

production:
  stage: deploy
  script:
    - docker exec idi2018_production_1 /bin/bash -c "cd /app; git pull --force"
    - docker exec idi2018_production_1 /bin/bash -c "uwsgi --reload /run/.pid"
    - docker exec idi2018_production_1 /bin/bash -c "nginx -s reload"
  environment:
    name: production
    url: https://production.local
  only:
  - master
  tags:
   - deployment

stages:
  - install
  - build
  - unit and integration tests
  - visual tests
  - deploy