version: '3'
services:
  gitlab-server:
    network_mode: bridge
    image: "gitlab/gitlab-ce:latest"
    hostname: "gitlab"
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - "/Users/srago/work/idi2018/gitlab/config:/etc/gitlab"
     - "/Users/srago/work/idi2018/gitlab/logs:/var/log/gitlab"
     - "/Users/srago/work/idi2018/gitlab/data:/var/opt/gitlab"
  gitlab-runner:
    network_mode: bridge
    image: "gitlab/gitlab-runner:latest"
    volumes:
     - "/Users/srago/work/idi2018/gitlab-runner/config:/etc/gitlab-runner"
     - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
     - gitlab-server
    links:
     - gitlab-server
     - selenium-grid
  selenium-grid:
    network_mode: bridge
    hostname: "selenium-grid"
    image: "selenium/standalone-chrome-debug:3.9.1-actinium"
    ports:
     - "4444:4444"
     - "5900:5900"
    volumes:
     - "/dev/shm:/dev/shm"
  production:
    network_mode: bridge
    hostname: "production"
    image: "sterago/alpine-flask"
    ports:
      - "8080:80"
    links:
     - gitlab-server
    volumes:
     - "/Users/srago/work/idi2018/app/:/app"
